# Spring properties
spring:
  application:
    name: microservice1

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

# HTTP Server
server:
  port: ${PORT:2222}
