# Spring properties
spring:
  application:
    name: microservice1
  kafka:
    bootstrap-servers: host.docker.internal:9092
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    hostname: afxm

# HTTP Server
server:
  port: ${PORT:8080}
  tomcat:
    max-threads: 10
  