# Spring properties
spring:
  application:
    name: microservice1

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: ${PORT:2222}
